import type { Template } from '../domain/types'

export const NEWS_EXTRA_TEMPLATE: Template = {
  schemaVersion: '1.0',
  type: 'template',
  programId: 'news_extra',
  programName: '뉴스외전',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  defaults: { scheduledSeconds: 3060, newsStartTime: '20:00:00' },
  items: [
    { id: 'sec_open', kind: 'sectionHeader', title: '오프닝', durationSeconds: 0, includeInRun: true },
    {
      id: 'title',
      kind: 'newsItem',
      category: '완제',
      reporter: '',
      title: '타이틀',
      durationSeconds: 20,
      notes: '',
      isDefaultItem: true,
      isEmphasis: false,
      includeInRun: true,
      flags: [],
    },
    {
      id: 'greet',
      kind: 'newsItem',
      category: '완제',
      reporter: '',
      title: '앵커 인사',
      durationSeconds: 20,
      notes: '',
      isDefaultItem: true,
      isEmphasis: false,
      includeInRun: true,
      flags: [],
    },
    { id: 'blank1', kind: 'blank', title: '', includeInRun: false },
    { id: 'end', kind: 'marker', title: '뉴스끝', includeInRun: false },
  ],
}

export const NEWS_ECONOMY_TEMPLATE: Template = {
  schemaVersion: '1.0',
  type: 'template',
  programId: 'news_economy',
  programName: '뉴스와 경제',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  defaults: { scheduledSeconds: 3060, newsStartTime: '20:00:00' },
  items: [
    { id: 'sec_open', kind: 'sectionHeader', title: '오프닝', durationSeconds: 0, includeInRun: true },
    {
      id: 'title',
      kind: 'newsItem',
      category: '완제',
      reporter: '',
      title: '타이틀',
      durationSeconds: 20,
      notes: '',
      isDefaultItem: true,
      isEmphasis: false,
      includeInRun: true,
      flags: [],
    },
    {
      id: 'cm',
      kind: 'newsItem',
      category: '완제',
      reporter: '',
      title: '광고/CM',
      durationSeconds: 60,
      notes: '',
      isDefaultItem: true,
      isEmphasis: false,
      includeInRun: true,
      flags: [],
    },
    {
      id: 'closing',
      kind: 'newsItem',
      category: '완제',
      reporter: '',
      title: '클로징',
      durationSeconds: 20,
      notes: '',
      isDefaultItem: true,
      isEmphasis: false,
      includeInRun: true,
      flags: [],
    },
    { id: 'end', kind: 'marker', title: '뉴스끝', includeInRun: false },
  ],
}

